package demo.service

import cats.effect.IO
import demo.api.Motd
import scala.util.Random

object MotdService:
  // Messages of the day kindly generated by ChatGPT :)
  private val messages = List(
    Motd("Every day is a new opportunity to create something amazing. Seize it!"),
    Motd("Progress, not perfection. Keep pushing forward."),
    Motd("The best way to predict the future is to create it. Dive in!"),
    Motd("Your potential is endless. Go do what you were created to do."),
    Motd("Embrace the journey, and the destination will find you."),
    Motd("Today is another chance to make a difference."),
    Motd("The best view comes after the hardest climb."),
    Motd("Every challenge faced is an opportunity for growth."),
    Motd("Stay curious, stay inspired, stay driven."),
    Motd("Your dreams don't have an expiration date. Take a deep breath and try again."),
    Motd("Life is 10% what happens to us and 90% how we react to it."),
    Motd("The future belongs to those who believe in the beauty of their dreams."),
    Motd("Success is not final, failure is not fatal: It is the courage to continue that counts."),
    Motd("Every moment is a fresh beginning. Embrace it.")
  )

  def random(): IO[Motd] =
    IO.pure(messages(Random.nextInt(messages.length)))
